name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy files via SCP (password auth)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 43.128.8.73
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "index.html,asset/"
          target: /www/wwwroot/43.128.8.73/
          rm: false
